apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |

    - Plex:
        icon: plex.png
        href: http://10.10.10.16:32400
        description: Watch movies and TV shows.
        server: localhost
        container: plex
        widgets:
          - type: tautulli
            url: http://172.16.1.1:8181
            key: aabbccddeeffgghhiijjkkllmmnnoo
          - type: uptimekuma
            url: http://172.16.1.2:8080
            slug: aaaaaaabbbbb

    - Entertainment:
        - My First Service:
            href: http://localhost/
            description: Homepage is awesome
        - widget:
            type: plex
            url: http://10.10.10.16:32400
            key: mytokenhere

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""