apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  #settings.yaml: ""
  settings.yaml: |
    theme: dark
    color: slate

    useEqualHeights: true

    layout:
      Hypervisor:
        header: true
        style: row
        columns: 4
      Home Automation:
        header: true
        style: row
        columns: 4
      Entertainment
        header: true
        style: row
        columns: 4

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |

    - Hypervisor:
        - Proxmox:
            href: http://10.10.20.2:8006
            icon: proxmox.svg
            description: My Lab of Labs
            widget:
              type: proxmox
              url: https://10.10.20.2:8006
              username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
              password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"
              node: pve 

    - Home Automation:
        - Home Assistant:
            icon: home-assistant.svg
            href: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
            description: home
            widget:
                type: homeassistant
                url: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
                key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}}"
        - UniFi:
            icon: https://play-lh.googleusercontent.com/DmgQvSdocOrGr0D0rxSBE9sqh23Fw3ck3BgKRN788cZnOKgcZlcEAFRYwmUbp6vMTVI
            href: "{{HOMEPAGE_VAR_UNIFI_PROTECT_URL}}"
            description: protect
        - Scryped:
            icon: https://www.scrypted.app/images/web_hi_res_512.png
            href: "{{HOMEPAGE_VAR_SCRYPTED_URL}}"
            description: mgmt console
        - Unifi Network:
            href: http://10.10.10.1
            icon: unifi.png
            description: Unifi
            widget:
              type: unifi
              url: https://10.10.10.1
              username: "{{HOMEPAGE_VAR_UNIFI_USERNAME}}"
              password: "{{HOMEPAGE_VAR_UNIFI_PASSWORD}}"
      - Entertainment:
          - Plex:
              icon: plex.png
              href: http://10.10.10.16:32400
              description: Watch movies and TV shows.
              server: localhost
              container: plex


  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default

  docker.yaml: ""