apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
data:
  HOMEPAGE_VAR_PROXMOX_PASSWORD: NWU2NzI0NWEtMDZlYy00MWRkLTg3ODYtOTQzNzRkNTYzMmJj
  HOMEPAGE_VAR_PROXMOX_USERNAME: aG9tZXBhZ2VAcGFtIWhvbWVwYWdl
  HOMEPAGE_VAR_UNIFI_USERNAME: aG9tZXBhZ2U=
  HOMEPAGE_VAR_UNIFI_PASSWORD: UEBzc3cwcmQxMjc4MTgyMw==
  HOMEPAGE_VAR_SCRYPTED_URL: aHR0cHM6Ly8xMC4xMC4xMC4yMzoxMDQ0My8=
  HOMEPAGE_VAR_UNIFI_PROTECT_URL: aHR0cHM6Ly8xMC4xMC4xMC4xMA==